<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240123183418 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE accion (id INT AUTO_INCREMENT NOT NULL, empresa_id INT DEFAULT NULL, nombre VARCHAR(255) NOT NULL, accion VARCHAR(255) NOT NULL, INDEX IDX_8A02E3B4521E1991 (empresa_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE agenda (id INT AUTO_INCREMENT NOT NULL, cuenta_id INT DEFAULT NULL, gestionar_id INT DEFAULT NULL, agendador_id INT DEFAULT NULL, sucursal_id INT DEFAULT NULL, status_id INT DEFAULT NULL, abogado_id INT DEFAULT NULL, reunion_id INT DEFAULT NULL, agenda_contacto_id INT DEFAULT NULL, sub_status_id INT DEFAULT NULL, canal_id INT DEFAULT NULL, empresa_id INT NOT NULL, campania VARCHAR(255) NOT NULL, nombre_cliente VARCHAR(255) DEFAULT NULL, email_cliente VARCHAR(255) DEFAULT NULL, telefono_cliente VARCHAR(255) DEFAULT NULL, ciudad_cliente VARCHAR(255) DEFAULT NULL, fecha_carga DATETIME DEFAULT NULL, fecha_asignado DATETIME DEFAULT NULL, detalle_cliente LONGTEXT DEFAULT NULL, monto NUMERIC(10, 0) DEFAULT NULL, observacion LONGTEXT DEFAULT NULL, rut_cliente VARCHAR(255) DEFAULT NULL, telefono_recado_cliente VARCHAR(255) DEFAULT NULL, fecha_contrato DATETIME DEFAULT NULL, lead VARCHAR(255) DEFAULT NULL, form_id VARCHAR(255) DEFAULT NULL, pago_actual NUMERIC(10, 0) DEFAULT NULL, INDEX IDX_2CEDC8779AEFF118 (cuenta_id), INDEX IDX_2CEDC877CA6D16AE (gestionar_id), INDEX IDX_2CEDC877BBF3C044 (agendador_id), INDEX IDX_2CEDC877279A5D5E (sucursal_id), INDEX IDX_2CEDC8776BF700BD (status_id), INDEX IDX_2CEDC877BDBF9863 (abogado_id), INDEX IDX_2CEDC8774E9B7368 (reunion_id), INDEX IDX_2CEDC877D88CBC6F (agenda_contacto_id), INDEX IDX_2CEDC87779FA4603 (sub_status_id), INDEX IDX_2CEDC87768DB5B2E (canal_id), INDEX IDX_2CEDC877521E1991 (empresa_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE agenda_contacto (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE agenda_observacion (id INT AUTO_INCREMENT NOT NULL, agenda_id INT NOT NULL, usuario_registro_id INT NOT NULL, status_id INT DEFAULT NULL, sub_status_id INT DEFAULT NULL, fecha_registro DATETIME NOT NULL, observacion LONGTEXT NOT NULL, INDEX IDX_BB645400EA67784A (agenda_id), INDEX IDX_BB6454001EEFD20 (usuario_registro_id), INDEX IDX_BB6454006BF700BD (status_id), INDEX IDX_BB64540079FA4603 (sub_status_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE agenda_status (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(255) NOT NULL, perfil INT NOT NULL, orden INT DEFAULT NULL, icon VARCHAR(255) DEFAULT NULL, color VARCHAR(255) DEFAULT NULL, vermas TINYINT(1) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE agenda_sub_status (id INT AUTO_INCREMENT NOT NULL, agenda_status_id INT DEFAULT NULL, nombre VARCHAR(30) NOT NULL, INDEX IDX_73CBC2A82129FD49 (agenda_status_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE canal (id INT AUTO_INCREMENT NOT NULL, empresa_id INT NOT NULL, usuario_registro_id INT NOT NULL, nombre VARCHAR(100) NOT NULL, estado TINYINT(1) NOT NULL, INDEX IDX_E181FB59521E1991 (empresa_id), INDEX IDX_E181FB591EEFD20 (usuario_registro_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cartera (id INT AUTO_INCREMENT NOT NULL, materia_id INT NOT NULL, nombre VARCHAR(20) NOT NULL, estado TINYINT(1) NOT NULL, orden INT NOT NULL, utilizado TINYINT(1) NOT NULL, asignado TINYINT(1) NOT NULL, INDEX IDX_EA7592ECB54DBBCB (materia_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE causa (id INT AUTO_INCREMENT NOT NULL, materia_estrategia_id INT DEFAULT NULL, juzgado_cuenta_id INT DEFAULT NULL, agenda_id INT NOT NULL, anexo_id INT DEFAULT NULL, id_causa VARCHAR(255) DEFAULT NULL, causa_nombre VARCHAR(255) NOT NULL, estado TINYINT(1) DEFAULT NULL, fecha_ultimo_ingreso DATETIME DEFAULT NULL, INDEX IDX_F7B7BBA6516A508C (materia_estrategia_id), INDEX IDX_F7B7BBA6AABE9B97 (juzgado_cuenta_id), INDEX IDX_F7B7BBA6EA67784A (agenda_id), INDEX IDX_F7B7BBA6C9348664 (anexo_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE causa_observacion (id INT AUTO_INCREMENT NOT NULL, causa_id INT NOT NULL, usuario_registro_id INT NOT NULL, contrato_id INT NOT NULL, fecha_registro DATETIME NOT NULL, observacion LONGTEXT NOT NULL, INDEX IDX_23D9D014E980B549 (causa_id), INDEX IDX_23D9D0141EEFD20 (usuario_registro_id), INDEX IDX_23D9D01470AE7BF1 (contrato_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ciudad (id INT AUTO_INCREMENT NOT NULL, region_id INT NOT NULL, nombre VARCHAR(50) NOT NULL, codigo VARCHAR(10) NOT NULL, INDEX IDX_8E86059E98260155 (region_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cliente_potencial (id INT AUTO_INCREMENT NOT NULL, form_id INT DEFAULT NULL, leadgen_id INT DEFAULT NULL, page_id INT DEFAULT NULL, created_time INT DEFAULT NULL, campos JSON DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cobranza (id INT AUTO_INCREMENT NOT NULL, funcion_id INT DEFAULT NULL, respuesta_id INT DEFAULT NULL, usuario_registro_id INT NOT NULL, contrato_id INT NOT NULL, fecha_hora DATETIME NOT NULL, fecha_compromiso DATETIME DEFAULT NULL, observacion LONGTEXT DEFAULT NULL, is_nulo TINYINT(1) DEFAULT NULL, fecha DATE DEFAULT NULL, INDEX IDX_AE20EF3D8C185C36 (funcion_id), INDEX IDX_AE20EF3DD9BA57A2 (respuesta_id), INDEX IDX_AE20EF3D1EEFD20 (usuario_registro_id), INDEX IDX_AE20EF3D70AE7BF1 (contrato_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cobranza_funcion (id INT AUTO_INCREMENT NOT NULL, empresa_id INT NOT NULL, nombre VARCHAR(255) NOT NULL, INDEX IDX_79CE3564521E1991 (empresa_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cobranza_respuesta (id INT AUTO_INCREMENT NOT NULL, empresa_id INT NOT NULL, nombre VARCHAR(255) NOT NULL, is_fecha_compromiso TINYINT(1) DEFAULT NULL, INDEX IDX_B792E924521E1991 (empresa_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE comuna (id INT AUTO_INCREMENT NOT NULL, ciudad_id INT NOT NULL, nombre VARCHAR(50) NOT NULL, codigo VARCHAR(10) NOT NULL, INDEX IDX_7E7DAE49E8608214 (ciudad_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE configuracion (id INT AUTO_INCREMENT NOT NULL, dia_fondo_fijo INT NOT NULL, host VARCHAR(255) DEFAULT NULL, access_token LONGTEXT DEFAULT NULL, verify_token LONGTEXT DEFAULT NULL, lotes INT DEFAULT NULL, valor_multa INT DEFAULT NULL, toku_id VARCHAR(255) DEFAULT NULL, toku_secret VARCHAR(255) DEFAULT NULL, max_dias_comision INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE contrato (id INT AUTO_INCREMENT NOT NULL, estado_civil_id INT DEFAULT NULL, situacion_laboral_id INT DEFAULT NULL, estrategia_juridica_id INT DEFAULT NULL, escritura_id INT DEFAULT NULL, agenda_id INT DEFAULT NULL, sucursal_id INT DEFAULT NULL, tramitador_id INT DEFAULT NULL, cliente_id INT DEFAULT NULL, pais_id INT DEFAULT NULL, vehiculo_id INT DEFAULT NULL, vivienda_id INT DEFAULT NULL, reunion_id INT DEFAULT NULL, id_lote_id INT DEFAULT NULL, ccomuna_id INT DEFAULT NULL, cciudad_id INT DEFAULT NULL, cregion_id INT DEFAULT NULL, cartera_id INT DEFAULT NULL, nombre VARCHAR(255) NOT NULL, email VARCHAR(255) DEFAULT NULL, telefono VARCHAR(255) NOT NULL, ciudad VARCHAR(255) DEFAULT NULL, rut VARCHAR(255) DEFAULT NULL, direccion VARCHAR(255) NOT NULL, comuna VARCHAR(255) NOT NULL, titulo_contrato VARCHAR(255) DEFAULT NULL, monto_nivel_deuda NUMERIC(10, 0) DEFAULT NULL, monto_contrato NUMERIC(10, 0) DEFAULT NULL, cuotas INT DEFAULT NULL, valor_cuota NUMERIC(10, 0) DEFAULT NULL, interes NUMERIC(5, 2) DEFAULT NULL, dia_pago INT DEFAULT NULL, fecha_creacion DATETIME DEFAULT NULL, clave_unica VARCHAR(255) DEFAULT NULL, telefono_recado VARCHAR(255) DEFAULT NULL, fecha_primer_pago DATETIME DEFAULT NULL, primera_cuota DOUBLE PRECISION DEFAULT NULL, fecha_primera_cuota DATE DEFAULT NULL, pdf VARCHAR(255) DEFAULT NULL, observacion LONGTEXT DEFAULT NULL, is_abono TINYINT(1) DEFAULT NULL, fecha_ultimo_pago DATE DEFAULT NULL, is_finalizado TINYINT(1) DEFAULT NULL, lote INT DEFAULT NULL, pdf_termino VARCHAR(255) DEFAULT NULL, fecha_termino DATETIME DEFAULT NULL, vigencia INT DEFAULT NULL, fecha_desiste DATETIME DEFAULT NULL, fecha_pdf_anexo DATETIME DEFAULT NULL, ultima_funcion VARCHAR(255) DEFAULT NULL, q_mov INT DEFAULT NULL, fecha_compromiso DATE DEFAULT NULL, folio VARCHAR(255) DEFAULT NULL, sexo VARCHAR(20) DEFAULT NULL, is_anexo TINYINT(1) DEFAULT NULL, proximo_vencimiento DATE DEFAULT NULL, fecha_ultima_gestion DATE DEFAULT NULL, pago_actual NUMERIC(10, 0) DEFAULT NULL, is_total TINYINT(1) DEFAULT NULL, cartera_orden INT NOT NULL, INDEX IDX_6669652375376D93 (estado_civil_id), INDEX IDX_666965238577D28 (situacion_laboral_id), INDEX IDX_6669652362144410 (estrategia_juridica_id), INDEX IDX_666965235D855194 (escritura_id), UNIQUE INDEX UNIQ_66696523EA67784A (agenda_id), INDEX IDX_66696523279A5D5E (sucursal_id), INDEX IDX_666965232D21BFE2 (tramitador_id), INDEX IDX_66696523DE734E51 (cliente_id), INDEX IDX_66696523C604D5C6 (pais_id), INDEX IDX_6669652325F7D575 (vehiculo_id), INDEX IDX_6669652381A75788 (vivienda_id), INDEX IDX_666965234E9B7368 (reunion_id), UNIQUE INDEX UNIQ_666965236FEFB00C (id_lote_id), INDEX IDX_6669652338692C4C (ccomuna_id), INDEX IDX_66696523D73341BF (cciudad_id), INDEX IDX_66696523A775C2FE (cregion_id), INDEX IDX_66696523A5A18135 (cartera_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE contrato_anexo (id INT AUTO_INCREMENT NOT NULL, contrato_id INT NOT NULL, fecha_creacion DATETIME NOT NULL, pdf VARCHAR(255) DEFAULT NULL, is_desiste TINYINT(1) NOT NULL, folio INT DEFAULT NULL, monto_contrato DOUBLE PRECISION DEFAULT NULL, is_abono TINYINT(1) DEFAULT NULL, abono DOUBLE PRECISION DEFAULT NULL, is_total TINYINT(1) DEFAULT NULL, n_cuotas INT DEFAULT NULL, valor_cuota DOUBLE PRECISION DEFAULT NULL, dias_pago INT DEFAULT NULL, fecha_primer_pago DATE DEFAULT NULL, vigencia INT DEFAULT NULL, observacion LONGTEXT DEFAULT NULL, tipo_anexo SMALLINT DEFAULT NULL, estado TINYINT(1) DEFAULT NULL, INDEX IDX_9DD8C30E70AE7BF1 (contrato_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE contrato_archivos (id INT AUTO_INCREMENT NOT NULL, usuario_registro_id INT NOT NULL, contrato_id INT NOT NULL, url VARCHAR(255) NOT NULL, fecha_subida DATETIME NOT NULL, INDEX IDX_D5B9B41B1EEFD20 (usuario_registro_id), INDEX IDX_D5B9B41B70AE7BF1 (contrato_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE contrato_audios (id INT AUTO_INCREMENT NOT NULL, contrato_id INT NOT NULL, usuario_registro_id INT NOT NULL, url VARCHAR(255) NOT NULL, INDEX IDX_4E43327E70AE7BF1 (contrato_id), INDEX IDX_4E43327E1EEFD20 (usuario_registro_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE contrato_mee (id INT AUTO_INCREMENT NOT NULL, contrato_id INT NOT NULL, mee_id INT DEFAULT NULL, mees LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', INDEX IDX_3B028F3670AE7BF1 (contrato_id), INDEX IDX_3B028F36C1825E09 (mee_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE contrato_rol (id INT AUTO_INCREMENT NOT NULL, juzgado_id INT DEFAULT NULL, contrato_id INT DEFAULT NULL, abogado_id INT NOT NULL, nombre_rol VARCHAR(255) NOT NULL, institucion_acreedora VARCHAR(255) NOT NULL, INDEX IDX_AF4B3B55B9A57363 (juzgado_id), INDEX IDX_AF4B3B5570AE7BF1 (contrato_id), INDEX IDX_AF4B3B55BDBF9863 (abogado_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE contrato_tramitador (id INT AUTO_INCREMENT NOT NULL, tramitadores_id INT NOT NULL, contrato_id INT NOT NULL, INDEX IDX_2A61EFE174A468AF (tramitadores_id), INDEX IDX_2A61EFE170AE7BF1 (contrato_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE contrato_vehiculo (id INT AUTO_INCREMENT NOT NULL, empresa_id INT DEFAULT NULL, nombre VARCHAR(255) NOT NULL, INDEX IDX_4CEA6AB521E1991 (empresa_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE contrato_vivienda (id INT AUTO_INCREMENT NOT NULL, empresa_id INT DEFAULT NULL, nombre VARCHAR(255) NOT NULL, INDEX IDX_E0CB1B76521E1991 (empresa_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cuenta (id INT AUTO_INCREMENT NOT NULL, empresa_id INT NOT NULL, nombre VARCHAR(255) NOT NULL, fecha_creacion DATETIME NOT NULL, fecha_ultimamodificacion DATETIME DEFAULT NULL, page_id DOUBLE PRECISION DEFAULT NULL, vigencia_contratos INT DEFAULT NULL, INDEX IDX_31C7BFCF521E1991 (empresa_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cuenta_corriente (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cuenta_materia (id INT AUTO_INCREMENT NOT NULL, cuenta_id INT NOT NULL, materia_id INT NOT NULL, estado TINYINT(1) DEFAULT NULL, INDEX IDX_FCAF66119AEFF118 (cuenta_id), INDEX IDX_FCAF6611B54DBBCB (materia_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cuota (id INT AUTO_INCREMENT NOT NULL, usuario_anulacion_id INT DEFAULT NULL, contrato_id INT NOT NULL, anexo_id INT DEFAULT NULL, numero INT NOT NULL, fecha_pago DATE NOT NULL, monto INT NOT NULL, pagado INT DEFAULT NULL, anular TINYINT(1) DEFAULT NULL, fecha_anulacion DATETIME DEFAULT NULL, is_multa TINYINT(1) DEFAULT NULL, invoice_id LONGTEXT DEFAULT NULL, INDEX IDX_763CCB0FBAF036CE (usuario_anulacion_id), INDEX IDX_763CCB0F70AE7BF1 (contrato_id), INDEX IDX_763CCB0FC9348664 (anexo_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dias_pago (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(255) NOT NULL, dias INT NOT NULL, orden INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE empresa (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(255) NOT NULL, rol VARCHAR(255) DEFAULT NULL, rut VARCHAR(20) NOT NULL, logo VARCHAR(255) DEFAULT NULL, fecha_ingreso DATETIME NOT NULL, fecha_ultimamodificacion DATETIME DEFAULT NULL, fecha_vigencia DATETIME NOT NULL, logo_alt VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE escritura (id INT AUTO_INCREMENT NOT NULL, empresa_id INT DEFAULT NULL, nombre VARCHAR(255) NOT NULL, INDEX IDX_2B6F7E72521E1991 (empresa_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE estado_civil (id INT AUTO_INCREMENT NOT NULL, empresa_id INT DEFAULT NULL, nombre VARCHAR(255) NOT NULL, INDEX IDX_F4222D84521E1991 (empresa_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE estrategia_juridica (id INT AUTO_INCREMENT NOT NULL, empresa_id INT DEFAULT NULL, linea_tiempo_id INT DEFAULT NULL, nombre VARCHAR(255) NOT NULL, precio DOUBLE PRECISION DEFAULT NULL, INDEX IDX_B649EC96521E1991 (empresa_id), INDEX IDX_B649EC9663AA8B75 (linea_tiempo_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE gestionar (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE importacion (id INT AUTO_INCREMENT NOT NULL, cuenta_id INT DEFAULT NULL, usuario_carga_id INT DEFAULT NULL, nombre VARCHAR(255) NOT NULL, fecha_carga DATETIME NOT NULL, url LONGTEXT NOT NULL, estado INT DEFAULT NULL, tipo_importacion INT DEFAULT NULL, INDEX IDX_F483A40E9AEFF118 (cuenta_id), INDEX IDX_F483A40E8924462A (usuario_carga_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inf_comision_cobradores (id INT AUTO_INCREMENT NOT NULL, contrato_id INT NOT NULL, cobranza_id INT NOT NULL, pago_id INT NOT NULL, cuota_id INT NOT NULL, sesion VARCHAR(255) NOT NULL, tiempo_gestion DOUBLE PRECISION NOT NULL, dias_mora INT NOT NULL, monto INT NOT NULL, INDEX IDX_2B0F631370AE7BF1 (contrato_id), INDEX IDX_2B0F6313A87A7CB6 (cobranza_id), INDEX IDX_2B0F631363FB8380 (pago_id), INDEX IDX_2B0F63136A7CF079 (cuota_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE juzgado (id INT AUTO_INCREMENT NOT NULL, empresa_id INT DEFAULT NULL, nombre VARCHAR(255) NOT NULL, INDEX IDX_695F140E521E1991 (empresa_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE juzgado_cuenta (id INT AUTO_INCREMENT NOT NULL, cuenta_id INT NOT NULL, juzgado_id INT NOT NULL, INDEX IDX_FCE1830F9AEFF118 (cuenta_id), INDEX IDX_FCE1830FB9A57363 (juzgado_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE linea_tiempo (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(100) NOT NULL, codigo VARCHAR(10) NOT NULL, orden INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE linea_tiempo_etapas (id INT AUTO_INCREMENT NOT NULL, linea_tiempo_id INT NOT NULL, nombre VARCHAR(255) NOT NULL, INDEX IDX_6535CAFD63AA8B75 (linea_tiempo_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE linea_tiempo_terminada (id INT AUTO_INCREMENT NOT NULL, causa_id INT NOT NULL, linea_tiempo_etapas_id INT NOT NULL, usuario_registro_id INT NOT NULL, estado TINYINT(1) NOT NULL, observacion LONGTEXT NOT NULL, fecha DATETIME NOT NULL, INDEX IDX_271DA87BE980B549 (causa_id), INDEX IDX_271DA87BBCFBDE31 (linea_tiempo_etapas_id), INDEX IDX_271DA87B1EEFD20 (usuario_registro_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lotes (id INT AUTO_INCREMENT NOT NULL, empresa_id INT DEFAULT NULL, nombre VARCHAR(50) NOT NULL, estado TINYINT(1) NOT NULL, orden INT NOT NULL, is_utilizado TINYINT(1) NOT NULL, is_asignado TINYINT(1) NOT NULL, INDEX IDX_7BDBF5EC521E1991 (empresa_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE materia (id INT AUTO_INCREMENT NOT NULL, empresa_id INT NOT NULL, nombre VARCHAR(50) NOT NULL, INDEX IDX_6DF05284521E1991 (empresa_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE materia_estrategia (id INT AUTO_INCREMENT NOT NULL, materia_id INT NOT NULL, estrategia_juridica_id INT NOT NULL, estado TINYINT(1) NOT NULL, INDEX IDX_8A1D519EB54DBBCB (materia_id), INDEX IDX_8A1D519E62144410 (estrategia_juridica_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE mee (id INT AUTO_INCREMENT NOT NULL, materia_estrategia_id INT NOT NULL, escritura_id INT NOT NULL, INDEX IDX_9A1C8B54516A508C (materia_estrategia_id), INDEX IDX_9A1C8B545D855194 (escritura_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE menu (id INT AUTO_INCREMENT NOT NULL, empresa_id INT NOT NULL, depende_de_id INT DEFAULT NULL, menu_cabezera_id INT DEFAULT NULL, modulo_id INT DEFAULT NULL, nombre VARCHAR(255) NOT NULL, icono VARCHAR(255) DEFAULT NULL, orden INT DEFAULT NULL, INDEX IDX_7D053A93521E1991 (empresa_id), INDEX IDX_7D053A93A53F971C (depende_de_id), INDEX IDX_7D053A93975F194D (menu_cabezera_id), INDEX IDX_7D053A93C07F55F5 (modulo_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE menu_cabezera (id INT AUTO_INCREMENT NOT NULL, empresa_id INT DEFAULT NULL, nombre VARCHAR(255) NOT NULL, INDEX IDX_431A2F13521E1991 (empresa_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE modulo (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(255) NOT NULL, ruta VARCHAR(255) NOT NULL, nombre_alt VARCHAR(255) DEFAULT NULL, descripcion VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE modulo_per (id INT AUTO_INCREMENT NOT NULL, empresa_id INT NOT NULL, modulo_id INT NOT NULL, nombre VARCHAR(255) NOT NULL, descripcion VARCHAR(255) NOT NULL, INDEX IDX_ABF22FE5521E1991 (empresa_id), INDEX IDX_ABF22FE5C07F55F5 (modulo_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pago (id INT AUTO_INCREMENT NOT NULL, pago_tipo_id INT NOT NULL, pago_canal_id INT NOT NULL, usuario_registro_id INT NOT NULL, cuenta_corriente_id INT NOT NULL, usuario_anulacion_id INT DEFAULT NULL, monto INT NOT NULL, boleta VARCHAR(255) DEFAULT NULL, observacion LONGTEXT DEFAULT NULL, fecha_pago DATETIME NOT NULL, hora_pago TIME NOT NULL, fecha_registro DATETIME NOT NULL, comprobante LONGTEXT DEFAULT NULL, fecha_ingreso DATE DEFAULT NULL, ncomprobante VARCHAR(255) DEFAULT NULL, anulado TINYINT(1) DEFAULT NULL, fecha_anulacion DATETIME DEFAULT NULL, INDEX IDX_F4DF5F3EC6690F67 (pago_tipo_id), INDEX IDX_F4DF5F3EFF66CCC7 (pago_canal_id), INDEX IDX_F4DF5F3E1EEFD20 (usuario_registro_id), INDEX IDX_F4DF5F3E1FB75A3B (cuenta_corriente_id), INDEX IDX_F4DF5F3EBAF036CE (usuario_anulacion_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pago_canal (id INT AUTO_INCREMENT NOT NULL, empresa_id INT DEFAULT NULL, nombre VARCHAR(255) NOT NULL, estado TINYINT(1) DEFAULT NULL, orden INT DEFAULT NULL, INDEX IDX_23705BC1521E1991 (empresa_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pago_cuotas (id INT AUTO_INCREMENT NOT NULL, pago_id INT NOT NULL, cuota_id INT NOT NULL, monto INT NOT NULL, INDEX IDX_75D1048763FB8380 (pago_id), INDEX IDX_75D104876A7CF079 (cuota_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pago_tipo (id INT AUTO_INCREMENT NOT NULL, empresa_id INT DEFAULT NULL, nombre VARCHAR(255) NOT NULL, orden INT DEFAULT NULL, estado TINYINT(1) DEFAULT NULL, is_boucher TINYINT(1) DEFAULT NULL, INDEX IDX_567222FB521E1991 (empresa_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pais (id INT AUTO_INCREMENT NOT NULL, empresa_id INT DEFAULT NULL, nombre VARCHAR(255) NOT NULL, orden INT DEFAULT NULL, INDEX IDX_7E5D2EFF521E1991 (empresa_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE primera_cuota (id INT AUTO_INCREMENT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE privilegio (id INT AUTO_INCREMENT NOT NULL, usuario_id INT NOT NULL, accion_id INT NOT NULL, modulo_per_id INT DEFAULT NULL, INDEX IDX_D0E1EA51DB38439E (usuario_id), INDEX IDX_D0E1EA513F4B5275 (accion_id), INDEX IDX_D0E1EA5188C77C8D (modulo_per_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE privilegio_tipousuario (id INT AUTO_INCREMENT NOT NULL, accion_id INT NOT NULL, tipousuario_id INT NOT NULL, modulo_per_id INT DEFAULT NULL, INDEX IDX_BE31D90E3F4B5275 (accion_id), INDEX IDX_BE31D90E74CA5DCD (tipousuario_id), INDEX IDX_BE31D90E88C77C8D (modulo_per_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE producto (id INT AUTO_INCREMENT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE recordatorio (id INT AUTO_INCREMENT NOT NULL, contrato_id INT NOT NULL, usuario_registro_id INT DEFAULT NULL, tipo_id INT NOT NULL, observacion LONGTEXT NOT NULL, fecha_creacion DATETIME NOT NULL, fecha_aviso DATE NOT NULL, leido TINYINT(1) NOT NULL, INDEX IDX_285981DF70AE7BF1 (contrato_id), INDEX IDX_285981DF1EEFD20 (usuario_registro_id), INDEX IDX_285981DFA9276E6C (tipo_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE recordatorio_tipo (id INT AUTO_INCREMENT NOT NULL, empresa_id INT DEFAULT NULL, nombre VARCHAR(50) NOT NULL, estado TINYINT(1) NOT NULL, INDEX IDX_4D78EF1F521E1991 (empresa_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE region (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(50) NOT NULL, codigo VARCHAR(3) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE reportes (id INT AUTO_INCREMENT NOT NULL, usuario_id INT NOT NULL, fecha_registro DATETIME NOT NULL, criterio JSON DEFAULT NULL, resultado JSON DEFAULT NULL, INDEX IDX_1D1D064DB38439E (usuario_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE reset_password_request (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, selector VARCHAR(20) NOT NULL, hashed_token VARCHAR(100) NOT NULL, requested_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', expires_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_7CE748AA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE reunion (id INT AUTO_INCREMENT NOT NULL, empresa_id INT DEFAULT NULL, nombre VARCHAR(255) NOT NULL, INDEX IDX_5B00A482521E1991 (empresa_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE situacion_laboral (id INT AUTO_INCREMENT NOT NULL, empresa_id INT DEFAULT NULL, nombre VARCHAR(255) NOT NULL, INDEX IDX_7F28676521E1991 (empresa_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sucursal (id INT AUTO_INCREMENT NOT NULL, cuenta_id INT DEFAULT NULL, nombre VARCHAR(255) NOT NULL, INDEX IDX_E99C6D569AEFF118 (cuenta_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ticket (id INT AUTO_INCREMENT NOT NULL, contrato_id INT NOT NULL, origen_id INT NOT NULL, destino_id INT DEFAULT NULL, encargado_id INT DEFAULT NULL, empresa_id INT NOT NULL, estado_id INT DEFAULT NULL, motivo VARCHAR(200) DEFAULT NULL, respuesta VARCHAR(200) DEFAULT NULL, detalle_cierre VARCHAR(200) DEFAULT NULL, fecha_nuevo DATETIME NOT NULL, fecha_asignado DATETIME DEFAULT NULL, fecha_respuesta DATETIME DEFAULT NULL, fecha_cierre DATETIME DEFAULT NULL, folio INT NOT NULL, folio_sac VARCHAR(20) DEFAULT NULL, INDEX IDX_97A0ADA370AE7BF1 (contrato_id), INDEX IDX_97A0ADA393529ECD (origen_id), INDEX IDX_97A0ADA3E4360615 (destino_id), INDEX IDX_97A0ADA34D75585E (encargado_id), INDEX IDX_97A0ADA3521E1991 (empresa_id), INDEX IDX_97A0ADA39F5A440B (estado_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ticket_estado (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(60) NOT NULL, icon VARCHAR(255) DEFAULT NULL, color VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ticket_historial (id INT AUTO_INCREMENT NOT NULL, ticket_id INT NOT NULL, usuario_registro_id INT NOT NULL, estado_id INT DEFAULT NULL, observacion VARCHAR(200) NOT NULL, fecha DATETIME DEFAULT NULL, INDEX IDX_BCAFDC18700047D2 (ticket_id), INDEX IDX_BCAFDC181EEFD20 (usuario_registro_id), INDEX IDX_BCAFDC189F5A440B (estado_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE usuario (id INT AUTO_INCREMENT NOT NULL, usuario_tipo_id INT NOT NULL, categoria_id INT DEFAULT NULL, status_id INT DEFAULT NULL, tipo_documento_id INT DEFAULT NULL, username VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, nombre VARCHAR(100) NOT NULL, estado TINYINT(1) NOT NULL, fecha_activacion DATETIME NOT NULL, correo VARCHAR(255) NOT NULL, token LONGTEXT DEFAULT NULL, empresa_actual INT DEFAULT NULL, fecha_no_disponible DATETIME DEFAULT NULL, whatsapp VARCHAR(255) DEFAULT NULL, telefono VARCHAR(255) DEFAULT NULL, rut VARCHAR(255) DEFAULT NULL, direccion VARCHAR(255) DEFAULT NULL, sexo VARCHAR(255) DEFAULT NULL, color VARCHAR(255) DEFAULT NULL, password_ant VARCHAR(255) DEFAULT NULL, lunes TINYINT(1) DEFAULT NULL, lunes_start TIME DEFAULT NULL, lunes_end TIME DEFAULT NULL, martes TINYINT(1) DEFAULT NULL, martes_start TIME DEFAULT NULL, martes_end TIME DEFAULT NULL, miercoles TINYINT(1) DEFAULT NULL, miercoles_start TIME DEFAULT NULL, miercoles_end TIME DEFAULT NULL, jueves TINYINT(1) DEFAULT NULL, jueves_start TIME DEFAULT NULL, jueves_end TIME DEFAULT NULL, viernes TINYINT(1) DEFAULT NULL, viernes_start TIME DEFAULT NULL, viernes_end TIME DEFAULT NULL, sabado TINYINT(1) DEFAULT NULL, sabado_start TIME DEFAULT NULL, sabado_end TIME DEFAULT NULL, domingo TINYINT(1) DEFAULT NULL, domingo_start TIME DEFAULT NULL, domingo_end TIME DEFAULT NULL, sobrecupo INT DEFAULT NULL, lotes JSON DEFAULT NULL, toku_id LONGTEXT DEFAULT NULL, fecha_nacimiento DATE DEFAULT NULL, fecha_aviso DATE DEFAULT NULL, UNIQUE INDEX UNIQ_2265B05DF85E0677 (username), INDEX IDX_2265B05DD001C42B (usuario_tipo_id), INDEX IDX_2265B05D3397707A (categoria_id), INDEX IDX_2265B05D6BF700BD (status_id), INDEX IDX_2265B05DF6939175 (tipo_documento_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE usuario_cartera (id INT AUTO_INCREMENT NOT NULL, usuario_id INT NOT NULL, cartera_id INT NOT NULL, INDEX IDX_935338ABDB38439E (usuario_id), INDEX IDX_935338ABA5A18135 (cartera_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE usuario_categoria (id INT AUTO_INCREMENT NOT NULL, empresa_id INT NOT NULL, nombre VARCHAR(255) NOT NULL, n_leads INT NOT NULL, INDEX IDX_C72BF83F521E1991 (empresa_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE usuario_cuenta (id INT AUTO_INCREMENT NOT NULL, cuenta_id INT DEFAULT NULL, usuario_id INT DEFAULT NULL, INDEX IDX_CBD55CC69AEFF118 (cuenta_id), INDEX IDX_CBD55CC6DB38439E (usuario_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE usuario_lote (id INT AUTO_INCREMENT NOT NULL, usuario_id INT DEFAULT NULL, lote_id INT NOT NULL, INDEX IDX_CCE488FDB38439E (usuario_id), INDEX IDX_CCE488FB172197C (lote_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE usuario_no_disponible (id INT AUTO_INCREMENT NOT NULL, usuario_id INT DEFAULT NULL, fecha DATE NOT NULL, hora_inicio TIME NOT NULL, hora_fin TIME NOT NULL, fecha_inicio DATE DEFAULT NULL, fecha_fin DATE DEFAULT NULL, anio INT DEFAULT NULL, mes INT DEFAULT NULL, dia INT DEFAULT NULL, concepto VARCHAR(255) NOT NULL, INDEX IDX_7C64E39CDB38439E (usuario_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE usuario_status (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE usuario_tipo (id INT AUTO_INCREMENT NOT NULL, menu_cabezera_id INT DEFAULT NULL, empresa_id INT DEFAULT NULL, nombre VARCHAR(100) NOT NULL, orden INT DEFAULT NULL, fijar TINYINT(1) NOT NULL, nombre_interno VARCHAR(255) NOT NULL, statues LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', INDEX IDX_19576757975F194D (menu_cabezera_id), INDEX IDX_19576757521E1991 (empresa_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE usuario_tipo_documento (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE usuario_usuariocategoria (id INT AUTO_INCREMENT NOT NULL, usuario_id INT NOT NULL, cuenta_id INT DEFAULT NULL, agenda_id INT DEFAULT NULL, INDEX IDX_892F60F1DB38439E (usuario_id), INDEX IDX_892F60F19AEFF118 (cuenta_id), INDEX IDX_892F60F1EA67784A (agenda_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE vencimiento (id INT AUTO_INCREMENT NOT NULL, empresa_id INT DEFAULT NULL, val_min INT DEFAULT NULL, val_max INT DEFAULT NULL, color VARCHAR(255) DEFAULT NULL, icono VARCHAR(255) DEFAULT NULL, INDEX IDX_66923AA8521E1991 (empresa_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE webhook (id INT AUTO_INCREMENT NOT NULL, verify_token VARCHAR(255) DEFAULT NULL, token VARCHAR(255) NOT NULL, user_token LONGTEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE accion ADD CONSTRAINT FK_8A02E3B4521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE agenda ADD CONSTRAINT FK_2CEDC8779AEFF118 FOREIGN KEY (cuenta_id) REFERENCES cuenta (id)');
        $this->addSql('ALTER TABLE agenda ADD CONSTRAINT FK_2CEDC877CA6D16AE FOREIGN KEY (gestionar_id) REFERENCES gestionar (id)');
        $this->addSql('ALTER TABLE agenda ADD CONSTRAINT FK_2CEDC877BBF3C044 FOREIGN KEY (agendador_id) REFERENCES usuario (id)');
        $this->addSql('ALTER TABLE agenda ADD CONSTRAINT FK_2CEDC877279A5D5E FOREIGN KEY (sucursal_id) REFERENCES sucursal (id)');
        $this->addSql('ALTER TABLE agenda ADD CONSTRAINT FK_2CEDC8776BF700BD FOREIGN KEY (status_id) REFERENCES agenda_status (id)');
        $this->addSql('ALTER TABLE agenda ADD CONSTRAINT FK_2CEDC877BDBF9863 FOREIGN KEY (abogado_id) REFERENCES usuario (id)');
        $this->addSql('ALTER TABLE agenda ADD CONSTRAINT FK_2CEDC8774E9B7368 FOREIGN KEY (reunion_id) REFERENCES reunion (id)');
        $this->addSql('ALTER TABLE agenda ADD CONSTRAINT FK_2CEDC877D88CBC6F FOREIGN KEY (agenda_contacto_id) REFERENCES agenda_contacto (id)');
        $this->addSql('ALTER TABLE agenda ADD CONSTRAINT FK_2CEDC87779FA4603 FOREIGN KEY (sub_status_id) REFERENCES agenda_sub_status (id)');
        $this->addSql('ALTER TABLE agenda ADD CONSTRAINT FK_2CEDC87768DB5B2E FOREIGN KEY (canal_id) REFERENCES canal (id)');
        $this->addSql('ALTER TABLE agenda ADD CONSTRAINT FK_2CEDC877521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE agenda_observacion ADD CONSTRAINT FK_BB645400EA67784A FOREIGN KEY (agenda_id) REFERENCES agenda (id)');
        $this->addSql('ALTER TABLE agenda_observacion ADD CONSTRAINT FK_BB6454001EEFD20 FOREIGN KEY (usuario_registro_id) REFERENCES usuario (id)');
        $this->addSql('ALTER TABLE agenda_observacion ADD CONSTRAINT FK_BB6454006BF700BD FOREIGN KEY (status_id) REFERENCES agenda_status (id)');
        $this->addSql('ALTER TABLE agenda_observacion ADD CONSTRAINT FK_BB64540079FA4603 FOREIGN KEY (sub_status_id) REFERENCES agenda_sub_status (id)');
        $this->addSql('ALTER TABLE agenda_sub_status ADD CONSTRAINT FK_73CBC2A82129FD49 FOREIGN KEY (agenda_status_id) REFERENCES agenda_status (id)');
        $this->addSql('ALTER TABLE canal ADD CONSTRAINT FK_E181FB59521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE canal ADD CONSTRAINT FK_E181FB591EEFD20 FOREIGN KEY (usuario_registro_id) REFERENCES usuario (id)');
        $this->addSql('ALTER TABLE cartera ADD CONSTRAINT FK_EA7592ECB54DBBCB FOREIGN KEY (materia_id) REFERENCES materia (id)');
        $this->addSql('ALTER TABLE causa ADD CONSTRAINT FK_F7B7BBA6516A508C FOREIGN KEY (materia_estrategia_id) REFERENCES materia_estrategia (id)');
        $this->addSql('ALTER TABLE causa ADD CONSTRAINT FK_F7B7BBA6AABE9B97 FOREIGN KEY (juzgado_cuenta_id) REFERENCES juzgado_cuenta (id)');
        $this->addSql('ALTER TABLE causa ADD CONSTRAINT FK_F7B7BBA6EA67784A FOREIGN KEY (agenda_id) REFERENCES agenda (id)');
        $this->addSql('ALTER TABLE causa ADD CONSTRAINT FK_F7B7BBA6C9348664 FOREIGN KEY (anexo_id) REFERENCES contrato_anexo (id)');
        $this->addSql('ALTER TABLE causa_observacion ADD CONSTRAINT FK_23D9D014E980B549 FOREIGN KEY (causa_id) REFERENCES causa (id)');
        $this->addSql('ALTER TABLE causa_observacion ADD CONSTRAINT FK_23D9D0141EEFD20 FOREIGN KEY (usuario_registro_id) REFERENCES usuario (id)');
        $this->addSql('ALTER TABLE causa_observacion ADD CONSTRAINT FK_23D9D01470AE7BF1 FOREIGN KEY (contrato_id) REFERENCES contrato (id)');
        $this->addSql('ALTER TABLE ciudad ADD CONSTRAINT FK_8E86059E98260155 FOREIGN KEY (region_id) REFERENCES region (id)');
        $this->addSql('ALTER TABLE cobranza ADD CONSTRAINT FK_AE20EF3D8C185C36 FOREIGN KEY (funcion_id) REFERENCES cobranza_funcion (id)');
        $this->addSql('ALTER TABLE cobranza ADD CONSTRAINT FK_AE20EF3DD9BA57A2 FOREIGN KEY (respuesta_id) REFERENCES cobranza_respuesta (id)');
        $this->addSql('ALTER TABLE cobranza ADD CONSTRAINT FK_AE20EF3D1EEFD20 FOREIGN KEY (usuario_registro_id) REFERENCES usuario (id)');
        $this->addSql('ALTER TABLE cobranza ADD CONSTRAINT FK_AE20EF3D70AE7BF1 FOREIGN KEY (contrato_id) REFERENCES contrato (id)');
        $this->addSql('ALTER TABLE cobranza_funcion ADD CONSTRAINT FK_79CE3564521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE cobranza_respuesta ADD CONSTRAINT FK_B792E924521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE comuna ADD CONSTRAINT FK_7E7DAE49E8608214 FOREIGN KEY (ciudad_id) REFERENCES ciudad (id)');
        $this->addSql('ALTER TABLE contrato ADD CONSTRAINT FK_6669652375376D93 FOREIGN KEY (estado_civil_id) REFERENCES estado_civil (id)');
        $this->addSql('ALTER TABLE contrato ADD CONSTRAINT FK_666965238577D28 FOREIGN KEY (situacion_laboral_id) REFERENCES situacion_laboral (id)');
        $this->addSql('ALTER TABLE contrato ADD CONSTRAINT FK_6669652362144410 FOREIGN KEY (estrategia_juridica_id) REFERENCES estrategia_juridica (id)');
        $this->addSql('ALTER TABLE contrato ADD CONSTRAINT FK_666965235D855194 FOREIGN KEY (escritura_id) REFERENCES escritura (id)');
        $this->addSql('ALTER TABLE contrato ADD CONSTRAINT FK_66696523EA67784A FOREIGN KEY (agenda_id) REFERENCES agenda (id)');
        $this->addSql('ALTER TABLE contrato ADD CONSTRAINT FK_66696523279A5D5E FOREIGN KEY (sucursal_id) REFERENCES sucursal (id)');
        $this->addSql('ALTER TABLE contrato ADD CONSTRAINT FK_666965232D21BFE2 FOREIGN KEY (tramitador_id) REFERENCES usuario (id)');
        $this->addSql('ALTER TABLE contrato ADD CONSTRAINT FK_66696523DE734E51 FOREIGN KEY (cliente_id) REFERENCES usuario (id)');
        $this->addSql('ALTER TABLE contrato ADD CONSTRAINT FK_66696523C604D5C6 FOREIGN KEY (pais_id) REFERENCES pais (id)');
        $this->addSql('ALTER TABLE contrato ADD CONSTRAINT FK_6669652325F7D575 FOREIGN KEY (vehiculo_id) REFERENCES contrato_vehiculo (id)');
        $this->addSql('ALTER TABLE contrato ADD CONSTRAINT FK_6669652381A75788 FOREIGN KEY (vivienda_id) REFERENCES contrato_vivienda (id)');
        $this->addSql('ALTER TABLE contrato ADD CONSTRAINT FK_666965234E9B7368 FOREIGN KEY (reunion_id) REFERENCES reunion (id)');
        $this->addSql('ALTER TABLE contrato ADD CONSTRAINT FK_666965236FEFB00C FOREIGN KEY (id_lote_id) REFERENCES lotes (id)');
        $this->addSql('ALTER TABLE contrato ADD CONSTRAINT FK_6669652338692C4C FOREIGN KEY (ccomuna_id) REFERENCES comuna (id)');
        $this->addSql('ALTER TABLE contrato ADD CONSTRAINT FK_66696523D73341BF FOREIGN KEY (cciudad_id) REFERENCES ciudad (id)');
        $this->addSql('ALTER TABLE contrato ADD CONSTRAINT FK_66696523A775C2FE FOREIGN KEY (cregion_id) REFERENCES region (id)');
        $this->addSql('ALTER TABLE contrato ADD CONSTRAINT FK_66696523A5A18135 FOREIGN KEY (cartera_id) REFERENCES cartera (id)');
        $this->addSql('ALTER TABLE contrato_anexo ADD CONSTRAINT FK_9DD8C30E70AE7BF1 FOREIGN KEY (contrato_id) REFERENCES contrato (id)');
        $this->addSql('ALTER TABLE contrato_archivos ADD CONSTRAINT FK_D5B9B41B1EEFD20 FOREIGN KEY (usuario_registro_id) REFERENCES usuario (id)');
        $this->addSql('ALTER TABLE contrato_archivos ADD CONSTRAINT FK_D5B9B41B70AE7BF1 FOREIGN KEY (contrato_id) REFERENCES contrato (id)');
        $this->addSql('ALTER TABLE contrato_audios ADD CONSTRAINT FK_4E43327E70AE7BF1 FOREIGN KEY (contrato_id) REFERENCES contrato (id)');
        $this->addSql('ALTER TABLE contrato_audios ADD CONSTRAINT FK_4E43327E1EEFD20 FOREIGN KEY (usuario_registro_id) REFERENCES usuario (id)');
        $this->addSql('ALTER TABLE contrato_mee ADD CONSTRAINT FK_3B028F3670AE7BF1 FOREIGN KEY (contrato_id) REFERENCES contrato (id)');
        $this->addSql('ALTER TABLE contrato_mee ADD CONSTRAINT FK_3B028F36C1825E09 FOREIGN KEY (mee_id) REFERENCES mee (id)');
        $this->addSql('ALTER TABLE contrato_rol ADD CONSTRAINT FK_AF4B3B55B9A57363 FOREIGN KEY (juzgado_id) REFERENCES juzgado (id)');
        $this->addSql('ALTER TABLE contrato_rol ADD CONSTRAINT FK_AF4B3B5570AE7BF1 FOREIGN KEY (contrato_id) REFERENCES contrato (id)');
        $this->addSql('ALTER TABLE contrato_rol ADD CONSTRAINT FK_AF4B3B55BDBF9863 FOREIGN KEY (abogado_id) REFERENCES usuario (id)');
        $this->addSql('ALTER TABLE contrato_tramitador ADD CONSTRAINT FK_2A61EFE174A468AF FOREIGN KEY (tramitadores_id) REFERENCES usuario (id)');
        $this->addSql('ALTER TABLE contrato_tramitador ADD CONSTRAINT FK_2A61EFE170AE7BF1 FOREIGN KEY (contrato_id) REFERENCES contrato (id)');
        $this->addSql('ALTER TABLE contrato_vehiculo ADD CONSTRAINT FK_4CEA6AB521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE contrato_vivienda ADD CONSTRAINT FK_E0CB1B76521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE cuenta ADD CONSTRAINT FK_31C7BFCF521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE cuenta_materia ADD CONSTRAINT FK_FCAF66119AEFF118 FOREIGN KEY (cuenta_id) REFERENCES cuenta (id)');
        $this->addSql('ALTER TABLE cuenta_materia ADD CONSTRAINT FK_FCAF6611B54DBBCB FOREIGN KEY (materia_id) REFERENCES materia (id)');
        $this->addSql('ALTER TABLE cuota ADD CONSTRAINT FK_763CCB0FBAF036CE FOREIGN KEY (usuario_anulacion_id) REFERENCES usuario (id)');
        $this->addSql('ALTER TABLE cuota ADD CONSTRAINT FK_763CCB0F70AE7BF1 FOREIGN KEY (contrato_id) REFERENCES contrato (id)');
        $this->addSql('ALTER TABLE cuota ADD CONSTRAINT FK_763CCB0FC9348664 FOREIGN KEY (anexo_id) REFERENCES contrato_anexo (id)');
        $this->addSql('ALTER TABLE escritura ADD CONSTRAINT FK_2B6F7E72521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE estado_civil ADD CONSTRAINT FK_F4222D84521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE estrategia_juridica ADD CONSTRAINT FK_B649EC96521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE estrategia_juridica ADD CONSTRAINT FK_B649EC9663AA8B75 FOREIGN KEY (linea_tiempo_id) REFERENCES linea_tiempo (id)');
        $this->addSql('ALTER TABLE importacion ADD CONSTRAINT FK_F483A40E9AEFF118 FOREIGN KEY (cuenta_id) REFERENCES cuenta (id)');
        $this->addSql('ALTER TABLE importacion ADD CONSTRAINT FK_F483A40E8924462A FOREIGN KEY (usuario_carga_id) REFERENCES usuario (id)');
        $this->addSql('ALTER TABLE inf_comision_cobradores ADD CONSTRAINT FK_2B0F631370AE7BF1 FOREIGN KEY (contrato_id) REFERENCES contrato (id)');
        $this->addSql('ALTER TABLE inf_comision_cobradores ADD CONSTRAINT FK_2B0F6313A87A7CB6 FOREIGN KEY (cobranza_id) REFERENCES cobranza (id)');
        $this->addSql('ALTER TABLE inf_comision_cobradores ADD CONSTRAINT FK_2B0F631363FB8380 FOREIGN KEY (pago_id) REFERENCES pago (id)');
        $this->addSql('ALTER TABLE inf_comision_cobradores ADD CONSTRAINT FK_2B0F63136A7CF079 FOREIGN KEY (cuota_id) REFERENCES cuota (id)');
        $this->addSql('ALTER TABLE juzgado ADD CONSTRAINT FK_695F140E521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE juzgado_cuenta ADD CONSTRAINT FK_FCE1830F9AEFF118 FOREIGN KEY (cuenta_id) REFERENCES cuenta (id)');
        $this->addSql('ALTER TABLE juzgado_cuenta ADD CONSTRAINT FK_FCE1830FB9A57363 FOREIGN KEY (juzgado_id) REFERENCES juzgado (id)');
        $this->addSql('ALTER TABLE linea_tiempo_etapas ADD CONSTRAINT FK_6535CAFD63AA8B75 FOREIGN KEY (linea_tiempo_id) REFERENCES linea_tiempo (id)');
        $this->addSql('ALTER TABLE linea_tiempo_terminada ADD CONSTRAINT FK_271DA87BE980B549 FOREIGN KEY (causa_id) REFERENCES causa (id)');
        $this->addSql('ALTER TABLE linea_tiempo_terminada ADD CONSTRAINT FK_271DA87BBCFBDE31 FOREIGN KEY (linea_tiempo_etapas_id) REFERENCES linea_tiempo_etapas (id)');
        $this->addSql('ALTER TABLE linea_tiempo_terminada ADD CONSTRAINT FK_271DA87B1EEFD20 FOREIGN KEY (usuario_registro_id) REFERENCES usuario (id)');
        $this->addSql('ALTER TABLE lotes ADD CONSTRAINT FK_7BDBF5EC521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE materia ADD CONSTRAINT FK_6DF05284521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE materia_estrategia ADD CONSTRAINT FK_8A1D519EB54DBBCB FOREIGN KEY (materia_id) REFERENCES materia (id)');
        $this->addSql('ALTER TABLE materia_estrategia ADD CONSTRAINT FK_8A1D519E62144410 FOREIGN KEY (estrategia_juridica_id) REFERENCES estrategia_juridica (id)');
        $this->addSql('ALTER TABLE mee ADD CONSTRAINT FK_9A1C8B54516A508C FOREIGN KEY (materia_estrategia_id) REFERENCES materia_estrategia (id)');
        $this->addSql('ALTER TABLE mee ADD CONSTRAINT FK_9A1C8B545D855194 FOREIGN KEY (escritura_id) REFERENCES escritura (id)');
        $this->addSql('ALTER TABLE menu ADD CONSTRAINT FK_7D053A93521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE menu ADD CONSTRAINT FK_7D053A93A53F971C FOREIGN KEY (depende_de_id) REFERENCES menu (id)');
        $this->addSql('ALTER TABLE menu ADD CONSTRAINT FK_7D053A93975F194D FOREIGN KEY (menu_cabezera_id) REFERENCES menu_cabezera (id)');
        $this->addSql('ALTER TABLE menu ADD CONSTRAINT FK_7D053A93C07F55F5 FOREIGN KEY (modulo_id) REFERENCES modulo (id)');
        $this->addSql('ALTER TABLE menu_cabezera ADD CONSTRAINT FK_431A2F13521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE modulo_per ADD CONSTRAINT FK_ABF22FE5521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE modulo_per ADD CONSTRAINT FK_ABF22FE5C07F55F5 FOREIGN KEY (modulo_id) REFERENCES modulo (id)');
        $this->addSql('ALTER TABLE pago ADD CONSTRAINT FK_F4DF5F3EC6690F67 FOREIGN KEY (pago_tipo_id) REFERENCES pago_tipo (id)');
        $this->addSql('ALTER TABLE pago ADD CONSTRAINT FK_F4DF5F3EFF66CCC7 FOREIGN KEY (pago_canal_id) REFERENCES pago_canal (id)');
        $this->addSql('ALTER TABLE pago ADD CONSTRAINT FK_F4DF5F3E1EEFD20 FOREIGN KEY (usuario_registro_id) REFERENCES usuario (id)');
        $this->addSql('ALTER TABLE pago ADD CONSTRAINT FK_F4DF5F3E1FB75A3B FOREIGN KEY (cuenta_corriente_id) REFERENCES cuenta_corriente (id)');
        $this->addSql('ALTER TABLE pago ADD CONSTRAINT FK_F4DF5F3EBAF036CE FOREIGN KEY (usuario_anulacion_id) REFERENCES usuario (id)');
        $this->addSql('ALTER TABLE pago_canal ADD CONSTRAINT FK_23705BC1521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE pago_cuotas ADD CONSTRAINT FK_75D1048763FB8380 FOREIGN KEY (pago_id) REFERENCES pago (id)');
        $this->addSql('ALTER TABLE pago_cuotas ADD CONSTRAINT FK_75D104876A7CF079 FOREIGN KEY (cuota_id) REFERENCES cuota (id)');
        $this->addSql('ALTER TABLE pago_tipo ADD CONSTRAINT FK_567222FB521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE pais ADD CONSTRAINT FK_7E5D2EFF521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE privilegio ADD CONSTRAINT FK_D0E1EA51DB38439E FOREIGN KEY (usuario_id) REFERENCES usuario (id)');
        $this->addSql('ALTER TABLE privilegio ADD CONSTRAINT FK_D0E1EA513F4B5275 FOREIGN KEY (accion_id) REFERENCES accion (id)');
        $this->addSql('ALTER TABLE privilegio ADD CONSTRAINT FK_D0E1EA5188C77C8D FOREIGN KEY (modulo_per_id) REFERENCES modulo_per (id)');
        $this->addSql('ALTER TABLE privilegio_tipousuario ADD CONSTRAINT FK_BE31D90E3F4B5275 FOREIGN KEY (accion_id) REFERENCES accion (id)');
        $this->addSql('ALTER TABLE privilegio_tipousuario ADD CONSTRAINT FK_BE31D90E74CA5DCD FOREIGN KEY (tipousuario_id) REFERENCES usuario_tipo (id)');
        $this->addSql('ALTER TABLE privilegio_tipousuario ADD CONSTRAINT FK_BE31D90E88C77C8D FOREIGN KEY (modulo_per_id) REFERENCES modulo_per (id)');
        $this->addSql('ALTER TABLE recordatorio ADD CONSTRAINT FK_285981DF70AE7BF1 FOREIGN KEY (contrato_id) REFERENCES contrato (id)');
        $this->addSql('ALTER TABLE recordatorio ADD CONSTRAINT FK_285981DF1EEFD20 FOREIGN KEY (usuario_registro_id) REFERENCES usuario (id)');
        $this->addSql('ALTER TABLE recordatorio ADD CONSTRAINT FK_285981DFA9276E6C FOREIGN KEY (tipo_id) REFERENCES recordatorio_tipo (id)');
        $this->addSql('ALTER TABLE recordatorio_tipo ADD CONSTRAINT FK_4D78EF1F521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE reportes ADD CONSTRAINT FK_1D1D064DB38439E FOREIGN KEY (usuario_id) REFERENCES usuario (id)');
        $this->addSql('ALTER TABLE reset_password_request ADD CONSTRAINT FK_7CE748AA76ED395 FOREIGN KEY (user_id) REFERENCES usuario (id)');
        $this->addSql('ALTER TABLE reunion ADD CONSTRAINT FK_5B00A482521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE situacion_laboral ADD CONSTRAINT FK_7F28676521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE sucursal ADD CONSTRAINT FK_E99C6D569AEFF118 FOREIGN KEY (cuenta_id) REFERENCES cuenta (id)');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA370AE7BF1 FOREIGN KEY (contrato_id) REFERENCES contrato (id)');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA393529ECD FOREIGN KEY (origen_id) REFERENCES usuario (id)');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA3E4360615 FOREIGN KEY (destino_id) REFERENCES usuario_tipo (id)');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA34D75585E FOREIGN KEY (encargado_id) REFERENCES usuario (id)');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA3521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA39F5A440B FOREIGN KEY (estado_id) REFERENCES ticket_estado (id)');
        $this->addSql('ALTER TABLE ticket_historial ADD CONSTRAINT FK_BCAFDC18700047D2 FOREIGN KEY (ticket_id) REFERENCES ticket (id)');
        $this->addSql('ALTER TABLE ticket_historial ADD CONSTRAINT FK_BCAFDC181EEFD20 FOREIGN KEY (usuario_registro_id) REFERENCES usuario (id)');
        $this->addSql('ALTER TABLE ticket_historial ADD CONSTRAINT FK_BCAFDC189F5A440B FOREIGN KEY (estado_id) REFERENCES ticket_estado (id)');
        $this->addSql('ALTER TABLE usuario ADD CONSTRAINT FK_2265B05DD001C42B FOREIGN KEY (usuario_tipo_id) REFERENCES usuario_tipo (id)');
        $this->addSql('ALTER TABLE usuario ADD CONSTRAINT FK_2265B05D3397707A FOREIGN KEY (categoria_id) REFERENCES usuario_categoria (id)');
        $this->addSql('ALTER TABLE usuario ADD CONSTRAINT FK_2265B05D6BF700BD FOREIGN KEY (status_id) REFERENCES usuario_status (id)');
        $this->addSql('ALTER TABLE usuario ADD CONSTRAINT FK_2265B05DF6939175 FOREIGN KEY (tipo_documento_id) REFERENCES usuario_tipo_documento (id)');
        $this->addSql('ALTER TABLE usuario_cartera ADD CONSTRAINT FK_935338ABDB38439E FOREIGN KEY (usuario_id) REFERENCES usuario (id)');
        $this->addSql('ALTER TABLE usuario_cartera ADD CONSTRAINT FK_935338ABA5A18135 FOREIGN KEY (cartera_id) REFERENCES cartera (id)');
        $this->addSql('ALTER TABLE usuario_categoria ADD CONSTRAINT FK_C72BF83F521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE usuario_cuenta ADD CONSTRAINT FK_CBD55CC69AEFF118 FOREIGN KEY (cuenta_id) REFERENCES cuenta (id)');
        $this->addSql('ALTER TABLE usuario_cuenta ADD CONSTRAINT FK_CBD55CC6DB38439E FOREIGN KEY (usuario_id) REFERENCES usuario (id)');
        $this->addSql('ALTER TABLE usuario_lote ADD CONSTRAINT FK_CCE488FDB38439E FOREIGN KEY (usuario_id) REFERENCES usuario (id)');
        $this->addSql('ALTER TABLE usuario_lote ADD CONSTRAINT FK_CCE488FB172197C FOREIGN KEY (lote_id) REFERENCES lotes (id)');
        $this->addSql('ALTER TABLE usuario_no_disponible ADD CONSTRAINT FK_7C64E39CDB38439E FOREIGN KEY (usuario_id) REFERENCES usuario (id)');
        $this->addSql('ALTER TABLE usuario_tipo ADD CONSTRAINT FK_19576757975F194D FOREIGN KEY (menu_cabezera_id) REFERENCES menu_cabezera (id)');
        $this->addSql('ALTER TABLE usuario_tipo ADD CONSTRAINT FK_19576757521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE usuario_usuariocategoria ADD CONSTRAINT FK_892F60F1DB38439E FOREIGN KEY (usuario_id) REFERENCES usuario (id)');
        $this->addSql('ALTER TABLE usuario_usuariocategoria ADD CONSTRAINT FK_892F60F19AEFF118 FOREIGN KEY (cuenta_id) REFERENCES cuenta (id)');
        $this->addSql('ALTER TABLE usuario_usuariocategoria ADD CONSTRAINT FK_892F60F1EA67784A FOREIGN KEY (agenda_id) REFERENCES agenda (id)');
        $this->addSql('ALTER TABLE vencimiento ADD CONSTRAINT FK_66923AA8521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id)');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE privilegio DROP FOREIGN KEY FK_D0E1EA513F4B5275');
        $this->addSql('ALTER TABLE privilegio_tipousuario DROP FOREIGN KEY FK_BE31D90E3F4B5275');
        $this->addSql('ALTER TABLE agenda_observacion DROP FOREIGN KEY FK_BB645400EA67784A');
        $this->addSql('ALTER TABLE causa DROP FOREIGN KEY FK_F7B7BBA6EA67784A');
        $this->addSql('ALTER TABLE contrato DROP FOREIGN KEY FK_66696523EA67784A');
        $this->addSql('ALTER TABLE usuario_usuariocategoria DROP FOREIGN KEY FK_892F60F1EA67784A');
        $this->addSql('ALTER TABLE agenda DROP FOREIGN KEY FK_2CEDC877D88CBC6F');
        $this->addSql('ALTER TABLE agenda DROP FOREIGN KEY FK_2CEDC8776BF700BD');
        $this->addSql('ALTER TABLE agenda_observacion DROP FOREIGN KEY FK_BB6454006BF700BD');
        $this->addSql('ALTER TABLE agenda_sub_status DROP FOREIGN KEY FK_73CBC2A82129FD49');
        $this->addSql('ALTER TABLE agenda DROP FOREIGN KEY FK_2CEDC87779FA4603');
        $this->addSql('ALTER TABLE agenda_observacion DROP FOREIGN KEY FK_BB64540079FA4603');
        $this->addSql('ALTER TABLE agenda DROP FOREIGN KEY FK_2CEDC87768DB5B2E');
        $this->addSql('ALTER TABLE contrato DROP FOREIGN KEY FK_66696523A5A18135');
        $this->addSql('ALTER TABLE usuario_cartera DROP FOREIGN KEY FK_935338ABA5A18135');
        $this->addSql('ALTER TABLE causa_observacion DROP FOREIGN KEY FK_23D9D014E980B549');
        $this->addSql('ALTER TABLE linea_tiempo_terminada DROP FOREIGN KEY FK_271DA87BE980B549');
        $this->addSql('ALTER TABLE comuna DROP FOREIGN KEY FK_7E7DAE49E8608214');
        $this->addSql('ALTER TABLE contrato DROP FOREIGN KEY FK_66696523D73341BF');
        $this->addSql('ALTER TABLE inf_comision_cobradores DROP FOREIGN KEY FK_2B0F6313A87A7CB6');
        $this->addSql('ALTER TABLE cobranza DROP FOREIGN KEY FK_AE20EF3D8C185C36');
        $this->addSql('ALTER TABLE cobranza DROP FOREIGN KEY FK_AE20EF3DD9BA57A2');
        $this->addSql('ALTER TABLE contrato DROP FOREIGN KEY FK_6669652338692C4C');
        $this->addSql('ALTER TABLE causa_observacion DROP FOREIGN KEY FK_23D9D01470AE7BF1');
        $this->addSql('ALTER TABLE cobranza DROP FOREIGN KEY FK_AE20EF3D70AE7BF1');
        $this->addSql('ALTER TABLE contrato_anexo DROP FOREIGN KEY FK_9DD8C30E70AE7BF1');
        $this->addSql('ALTER TABLE contrato_archivos DROP FOREIGN KEY FK_D5B9B41B70AE7BF1');
        $this->addSql('ALTER TABLE contrato_audios DROP FOREIGN KEY FK_4E43327E70AE7BF1');
        $this->addSql('ALTER TABLE contrato_mee DROP FOREIGN KEY FK_3B028F3670AE7BF1');
        $this->addSql('ALTER TABLE contrato_rol DROP FOREIGN KEY FK_AF4B3B5570AE7BF1');
        $this->addSql('ALTER TABLE contrato_tramitador DROP FOREIGN KEY FK_2A61EFE170AE7BF1');
        $this->addSql('ALTER TABLE cuota DROP FOREIGN KEY FK_763CCB0F70AE7BF1');
        $this->addSql('ALTER TABLE inf_comision_cobradores DROP FOREIGN KEY FK_2B0F631370AE7BF1');
        $this->addSql('ALTER TABLE recordatorio DROP FOREIGN KEY FK_285981DF70AE7BF1');
        $this->addSql('ALTER TABLE ticket DROP FOREIGN KEY FK_97A0ADA370AE7BF1');
        $this->addSql('ALTER TABLE causa DROP FOREIGN KEY FK_F7B7BBA6C9348664');
        $this->addSql('ALTER TABLE cuota DROP FOREIGN KEY FK_763CCB0FC9348664');
        $this->addSql('ALTER TABLE contrato DROP FOREIGN KEY FK_6669652325F7D575');
        $this->addSql('ALTER TABLE contrato DROP FOREIGN KEY FK_6669652381A75788');
        $this->addSql('ALTER TABLE agenda DROP FOREIGN KEY FK_2CEDC8779AEFF118');
        $this->addSql('ALTER TABLE cuenta_materia DROP FOREIGN KEY FK_FCAF66119AEFF118');
        $this->addSql('ALTER TABLE importacion DROP FOREIGN KEY FK_F483A40E9AEFF118');
        $this->addSql('ALTER TABLE juzgado_cuenta DROP FOREIGN KEY FK_FCE1830F9AEFF118');
        $this->addSql('ALTER TABLE sucursal DROP FOREIGN KEY FK_E99C6D569AEFF118');
        $this->addSql('ALTER TABLE usuario_cuenta DROP FOREIGN KEY FK_CBD55CC69AEFF118');
        $this->addSql('ALTER TABLE usuario_usuariocategoria DROP FOREIGN KEY FK_892F60F19AEFF118');
        $this->addSql('ALTER TABLE pago DROP FOREIGN KEY FK_F4DF5F3E1FB75A3B');
        $this->addSql('ALTER TABLE inf_comision_cobradores DROP FOREIGN KEY FK_2B0F63136A7CF079');
        $this->addSql('ALTER TABLE pago_cuotas DROP FOREIGN KEY FK_75D104876A7CF079');
        $this->addSql('ALTER TABLE accion DROP FOREIGN KEY FK_8A02E3B4521E1991');
        $this->addSql('ALTER TABLE agenda DROP FOREIGN KEY FK_2CEDC877521E1991');
        $this->addSql('ALTER TABLE canal DROP FOREIGN KEY FK_E181FB59521E1991');
        $this->addSql('ALTER TABLE cobranza_funcion DROP FOREIGN KEY FK_79CE3564521E1991');
        $this->addSql('ALTER TABLE cobranza_respuesta DROP FOREIGN KEY FK_B792E924521E1991');
        $this->addSql('ALTER TABLE contrato_vehiculo DROP FOREIGN KEY FK_4CEA6AB521E1991');
        $this->addSql('ALTER TABLE contrato_vivienda DROP FOREIGN KEY FK_E0CB1B76521E1991');
        $this->addSql('ALTER TABLE cuenta DROP FOREIGN KEY FK_31C7BFCF521E1991');
        $this->addSql('ALTER TABLE escritura DROP FOREIGN KEY FK_2B6F7E72521E1991');
        $this->addSql('ALTER TABLE estado_civil DROP FOREIGN KEY FK_F4222D84521E1991');
        $this->addSql('ALTER TABLE estrategia_juridica DROP FOREIGN KEY FK_B649EC96521E1991');
        $this->addSql('ALTER TABLE juzgado DROP FOREIGN KEY FK_695F140E521E1991');
        $this->addSql('ALTER TABLE lotes DROP FOREIGN KEY FK_7BDBF5EC521E1991');
        $this->addSql('ALTER TABLE materia DROP FOREIGN KEY FK_6DF05284521E1991');
        $this->addSql('ALTER TABLE menu DROP FOREIGN KEY FK_7D053A93521E1991');
        $this->addSql('ALTER TABLE menu_cabezera DROP FOREIGN KEY FK_431A2F13521E1991');
        $this->addSql('ALTER TABLE modulo_per DROP FOREIGN KEY FK_ABF22FE5521E1991');
        $this->addSql('ALTER TABLE pago_canal DROP FOREIGN KEY FK_23705BC1521E1991');
        $this->addSql('ALTER TABLE pago_tipo DROP FOREIGN KEY FK_567222FB521E1991');
        $this->addSql('ALTER TABLE pais DROP FOREIGN KEY FK_7E5D2EFF521E1991');
        $this->addSql('ALTER TABLE recordatorio_tipo DROP FOREIGN KEY FK_4D78EF1F521E1991');
        $this->addSql('ALTER TABLE reunion DROP FOREIGN KEY FK_5B00A482521E1991');
        $this->addSql('ALTER TABLE situacion_laboral DROP FOREIGN KEY FK_7F28676521E1991');
        $this->addSql('ALTER TABLE ticket DROP FOREIGN KEY FK_97A0ADA3521E1991');
        $this->addSql('ALTER TABLE usuario_categoria DROP FOREIGN KEY FK_C72BF83F521E1991');
        $this->addSql('ALTER TABLE usuario_tipo DROP FOREIGN KEY FK_19576757521E1991');
        $this->addSql('ALTER TABLE vencimiento DROP FOREIGN KEY FK_66923AA8521E1991');
        $this->addSql('ALTER TABLE contrato DROP FOREIGN KEY FK_666965235D855194');
        $this->addSql('ALTER TABLE mee DROP FOREIGN KEY FK_9A1C8B545D855194');
        $this->addSql('ALTER TABLE contrato DROP FOREIGN KEY FK_6669652375376D93');
        $this->addSql('ALTER TABLE contrato DROP FOREIGN KEY FK_6669652362144410');
        $this->addSql('ALTER TABLE materia_estrategia DROP FOREIGN KEY FK_8A1D519E62144410');
        $this->addSql('ALTER TABLE agenda DROP FOREIGN KEY FK_2CEDC877CA6D16AE');
        $this->addSql('ALTER TABLE contrato_rol DROP FOREIGN KEY FK_AF4B3B55B9A57363');
        $this->addSql('ALTER TABLE juzgado_cuenta DROP FOREIGN KEY FK_FCE1830FB9A57363');
        $this->addSql('ALTER TABLE causa DROP FOREIGN KEY FK_F7B7BBA6AABE9B97');
        $this->addSql('ALTER TABLE estrategia_juridica DROP FOREIGN KEY FK_B649EC9663AA8B75');
        $this->addSql('ALTER TABLE linea_tiempo_etapas DROP FOREIGN KEY FK_6535CAFD63AA8B75');
        $this->addSql('ALTER TABLE linea_tiempo_terminada DROP FOREIGN KEY FK_271DA87BBCFBDE31');
        $this->addSql('ALTER TABLE contrato DROP FOREIGN KEY FK_666965236FEFB00C');
        $this->addSql('ALTER TABLE usuario_lote DROP FOREIGN KEY FK_CCE488FB172197C');
        $this->addSql('ALTER TABLE cartera DROP FOREIGN KEY FK_EA7592ECB54DBBCB');
        $this->addSql('ALTER TABLE cuenta_materia DROP FOREIGN KEY FK_FCAF6611B54DBBCB');
        $this->addSql('ALTER TABLE materia_estrategia DROP FOREIGN KEY FK_8A1D519EB54DBBCB');
        $this->addSql('ALTER TABLE causa DROP FOREIGN KEY FK_F7B7BBA6516A508C');
        $this->addSql('ALTER TABLE mee DROP FOREIGN KEY FK_9A1C8B54516A508C');
        $this->addSql('ALTER TABLE contrato_mee DROP FOREIGN KEY FK_3B028F36C1825E09');
        $this->addSql('ALTER TABLE menu DROP FOREIGN KEY FK_7D053A93A53F971C');
        $this->addSql('ALTER TABLE menu DROP FOREIGN KEY FK_7D053A93975F194D');
        $this->addSql('ALTER TABLE usuario_tipo DROP FOREIGN KEY FK_19576757975F194D');
        $this->addSql('ALTER TABLE menu DROP FOREIGN KEY FK_7D053A93C07F55F5');
        $this->addSql('ALTER TABLE modulo_per DROP FOREIGN KEY FK_ABF22FE5C07F55F5');
        $this->addSql('ALTER TABLE privilegio DROP FOREIGN KEY FK_D0E1EA5188C77C8D');
        $this->addSql('ALTER TABLE privilegio_tipousuario DROP FOREIGN KEY FK_BE31D90E88C77C8D');
        $this->addSql('ALTER TABLE inf_comision_cobradores DROP FOREIGN KEY FK_2B0F631363FB8380');
        $this->addSql('ALTER TABLE pago_cuotas DROP FOREIGN KEY FK_75D1048763FB8380');
        $this->addSql('ALTER TABLE pago DROP FOREIGN KEY FK_F4DF5F3EFF66CCC7');
        $this->addSql('ALTER TABLE pago DROP FOREIGN KEY FK_F4DF5F3EC6690F67');
        $this->addSql('ALTER TABLE contrato DROP FOREIGN KEY FK_66696523C604D5C6');
        $this->addSql('ALTER TABLE recordatorio DROP FOREIGN KEY FK_285981DFA9276E6C');
        $this->addSql('ALTER TABLE ciudad DROP FOREIGN KEY FK_8E86059E98260155');
        $this->addSql('ALTER TABLE contrato DROP FOREIGN KEY FK_66696523A775C2FE');
        $this->addSql('ALTER TABLE agenda DROP FOREIGN KEY FK_2CEDC8774E9B7368');
        $this->addSql('ALTER TABLE contrato DROP FOREIGN KEY FK_666965234E9B7368');
        $this->addSql('ALTER TABLE contrato DROP FOREIGN KEY FK_666965238577D28');
        $this->addSql('ALTER TABLE agenda DROP FOREIGN KEY FK_2CEDC877279A5D5E');
        $this->addSql('ALTER TABLE contrato DROP FOREIGN KEY FK_66696523279A5D5E');
        $this->addSql('ALTER TABLE ticket_historial DROP FOREIGN KEY FK_BCAFDC18700047D2');
        $this->addSql('ALTER TABLE ticket DROP FOREIGN KEY FK_97A0ADA39F5A440B');
        $this->addSql('ALTER TABLE ticket_historial DROP FOREIGN KEY FK_BCAFDC189F5A440B');
        $this->addSql('ALTER TABLE agenda DROP FOREIGN KEY FK_2CEDC877BBF3C044');
        $this->addSql('ALTER TABLE agenda DROP FOREIGN KEY FK_2CEDC877BDBF9863');
        $this->addSql('ALTER TABLE agenda_observacion DROP FOREIGN KEY FK_BB6454001EEFD20');
        $this->addSql('ALTER TABLE canal DROP FOREIGN KEY FK_E181FB591EEFD20');
        $this->addSql('ALTER TABLE causa_observacion DROP FOREIGN KEY FK_23D9D0141EEFD20');
        $this->addSql('ALTER TABLE cobranza DROP FOREIGN KEY FK_AE20EF3D1EEFD20');
        $this->addSql('ALTER TABLE contrato DROP FOREIGN KEY FK_666965232D21BFE2');
        $this->addSql('ALTER TABLE contrato DROP FOREIGN KEY FK_66696523DE734E51');
        $this->addSql('ALTER TABLE contrato_archivos DROP FOREIGN KEY FK_D5B9B41B1EEFD20');
        $this->addSql('ALTER TABLE contrato_audios DROP FOREIGN KEY FK_4E43327E1EEFD20');
        $this->addSql('ALTER TABLE contrato_rol DROP FOREIGN KEY FK_AF4B3B55BDBF9863');
        $this->addSql('ALTER TABLE contrato_tramitador DROP FOREIGN KEY FK_2A61EFE174A468AF');
        $this->addSql('ALTER TABLE cuota DROP FOREIGN KEY FK_763CCB0FBAF036CE');
        $this->addSql('ALTER TABLE importacion DROP FOREIGN KEY FK_F483A40E8924462A');
        $this->addSql('ALTER TABLE linea_tiempo_terminada DROP FOREIGN KEY FK_271DA87B1EEFD20');
        $this->addSql('ALTER TABLE pago DROP FOREIGN KEY FK_F4DF5F3E1EEFD20');
        $this->addSql('ALTER TABLE pago DROP FOREIGN KEY FK_F4DF5F3EBAF036CE');
        $this->addSql('ALTER TABLE privilegio DROP FOREIGN KEY FK_D0E1EA51DB38439E');
        $this->addSql('ALTER TABLE recordatorio DROP FOREIGN KEY FK_285981DF1EEFD20');
        $this->addSql('ALTER TABLE reportes DROP FOREIGN KEY FK_1D1D064DB38439E');
        $this->addSql('ALTER TABLE reset_password_request DROP FOREIGN KEY FK_7CE748AA76ED395');
        $this->addSql('ALTER TABLE ticket DROP FOREIGN KEY FK_97A0ADA393529ECD');
        $this->addSql('ALTER TABLE ticket DROP FOREIGN KEY FK_97A0ADA34D75585E');
        $this->addSql('ALTER TABLE ticket_historial DROP FOREIGN KEY FK_BCAFDC181EEFD20');
        $this->addSql('ALTER TABLE usuario_cartera DROP FOREIGN KEY FK_935338ABDB38439E');
        $this->addSql('ALTER TABLE usuario_cuenta DROP FOREIGN KEY FK_CBD55CC6DB38439E');
        $this->addSql('ALTER TABLE usuario_lote DROP FOREIGN KEY FK_CCE488FDB38439E');
        $this->addSql('ALTER TABLE usuario_no_disponible DROP FOREIGN KEY FK_7C64E39CDB38439E');
        $this->addSql('ALTER TABLE usuario_usuariocategoria DROP FOREIGN KEY FK_892F60F1DB38439E');
        $this->addSql('ALTER TABLE usuario DROP FOREIGN KEY FK_2265B05D3397707A');
        $this->addSql('ALTER TABLE usuario DROP FOREIGN KEY FK_2265B05D6BF700BD');
        $this->addSql('ALTER TABLE privilegio_tipousuario DROP FOREIGN KEY FK_BE31D90E74CA5DCD');
        $this->addSql('ALTER TABLE ticket DROP FOREIGN KEY FK_97A0ADA3E4360615');
        $this->addSql('ALTER TABLE usuario DROP FOREIGN KEY FK_2265B05DD001C42B');
        $this->addSql('ALTER TABLE usuario DROP FOREIGN KEY FK_2265B05DF6939175');
        $this->addSql('DROP TABLE accion');
        $this->addSql('DROP TABLE agenda');
        $this->addSql('DROP TABLE agenda_contacto');
        $this->addSql('DROP TABLE agenda_observacion');
        $this->addSql('DROP TABLE agenda_status');
        $this->addSql('DROP TABLE agenda_sub_status');
        $this->addSql('DROP TABLE canal');
        $this->addSql('DROP TABLE cartera');
        $this->addSql('DROP TABLE causa');
        $this->addSql('DROP TABLE causa_observacion');
        $this->addSql('DROP TABLE ciudad');
        $this->addSql('DROP TABLE cliente_potencial');
        $this->addSql('DROP TABLE cobranza');
        $this->addSql('DROP TABLE cobranza_funcion');
        $this->addSql('DROP TABLE cobranza_respuesta');
        $this->addSql('DROP TABLE comuna');
        $this->addSql('DROP TABLE configuracion');
        $this->addSql('DROP TABLE contrato');
        $this->addSql('DROP TABLE contrato_anexo');
        $this->addSql('DROP TABLE contrato_archivos');
        $this->addSql('DROP TABLE contrato_audios');
        $this->addSql('DROP TABLE contrato_mee');
        $this->addSql('DROP TABLE contrato_rol');
        $this->addSql('DROP TABLE contrato_tramitador');
        $this->addSql('DROP TABLE contrato_vehiculo');
        $this->addSql('DROP TABLE contrato_vivienda');
        $this->addSql('DROP TABLE cuenta');
        $this->addSql('DROP TABLE cuenta_corriente');
        $this->addSql('DROP TABLE cuenta_materia');
        $this->addSql('DROP TABLE cuota');
        $this->addSql('DROP TABLE dias_pago');
        $this->addSql('DROP TABLE empresa');
        $this->addSql('DROP TABLE escritura');
        $this->addSql('DROP TABLE estado_civil');
        $this->addSql('DROP TABLE estrategia_juridica');
        $this->addSql('DROP TABLE gestionar');
        $this->addSql('DROP TABLE importacion');
        $this->addSql('DROP TABLE inf_comision_cobradores');
        $this->addSql('DROP TABLE juzgado');
        $this->addSql('DROP TABLE juzgado_cuenta');
        $this->addSql('DROP TABLE linea_tiempo');
        $this->addSql('DROP TABLE linea_tiempo_etapas');
        $this->addSql('DROP TABLE linea_tiempo_terminada');
        $this->addSql('DROP TABLE lotes');
        $this->addSql('DROP TABLE materia');
        $this->addSql('DROP TABLE materia_estrategia');
        $this->addSql('DROP TABLE mee');
        $this->addSql('DROP TABLE menu');
        $this->addSql('DROP TABLE menu_cabezera');
        $this->addSql('DROP TABLE modulo');
        $this->addSql('DROP TABLE modulo_per');
        $this->addSql('DROP TABLE pago');
        $this->addSql('DROP TABLE pago_canal');
        $this->addSql('DROP TABLE pago_cuotas');
        $this->addSql('DROP TABLE pago_tipo');
        $this->addSql('DROP TABLE pais');
        $this->addSql('DROP TABLE primera_cuota');
        $this->addSql('DROP TABLE privilegio');
        $this->addSql('DROP TABLE privilegio_tipousuario');
        $this->addSql('DROP TABLE producto');
        $this->addSql('DROP TABLE recordatorio');
        $this->addSql('DROP TABLE recordatorio_tipo');
        $this->addSql('DROP TABLE region');
        $this->addSql('DROP TABLE reportes');
        $this->addSql('DROP TABLE reset_password_request');
        $this->addSql('DROP TABLE reunion');
        $this->addSql('DROP TABLE situacion_laboral');
        $this->addSql('DROP TABLE sucursal');
        $this->addSql('DROP TABLE ticket');
        $this->addSql('DROP TABLE ticket_estado');
        $this->addSql('DROP TABLE ticket_historial');
        $this->addSql('DROP TABLE usuario');
        $this->addSql('DROP TABLE usuario_cartera');
        $this->addSql('DROP TABLE usuario_categoria');
        $this->addSql('DROP TABLE usuario_cuenta');
        $this->addSql('DROP TABLE usuario_lote');
        $this->addSql('DROP TABLE usuario_no_disponible');
        $this->addSql('DROP TABLE usuario_status');
        $this->addSql('DROP TABLE usuario_tipo');
        $this->addSql('DROP TABLE usuario_tipo_documento');
        $this->addSql('DROP TABLE usuario_usuariocategoria');
        $this->addSql('DROP TABLE vencimiento');
        $this->addSql('DROP TABLE webhook');
    }
}
